[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wire = { path = "../wire" }

[build-dependencies]
wire-build = { path = "../wire-build" }
