[package]
name = "wire-build"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "main"
doc = false
path = "src/main.rs"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
heck = "0.5.0"
